### ISSUE TITLE
Navbarda font-size katta bo`lib qolgan

### ISSUE THREAD

**Issue by oybek94** [vayvoo/CrowdFund-project--0103-#1]
Navbarda font-size katta bolib qolgan. 
Yechim: 
`.navitem {font-size: 13px;}`
 
https://github.com/vayvoo/CrowdFund-project--0103-/blob/a7903a1ade2ca8908a239b219d7b4b25a3b6c63a/css/style.css#L89

**Comment by vayvoo** [comment]
fixed :+1:
