### ISSUE TITLE
Gradientga shaffoflik berilmagan.

### ISSUE THREAD

**Issue by oybek94** [vayvoo/CrowdFund-project--0103-#2]
Dizaynga kora gradientga 0.6 shaffoflik berilishi kerak. 
Buni togirlash uchun: 
`.navbar {background: linear-gradient(180deg, rgb(0 0 0 / 60%) 0%, rgba(0, 0, 0, 0.006) 100%);}` deb yozish kerak
https://github.com/vayvoo/CrowdFund-project--0103-/blob/a7903a1ade2ca8908a239b219d7b4b25a3b6c63a/css/style.css#L80

**Comment by vayvoo** [comment]
fixed
