### ISSUE TITLE
Product-info

### ISSUE THREAD

**Issue by AbdunazarovM** [vayvoo/CrowdFund-project--0103-#5]
https://github.com/vayvoo/CrowdFund-project--0103-/blob/ce2603f9bd4418a4aaede2e94583ad320129f569/css/style.css#L349
margin-top bilan emas margin-bottom ishlang 
Product-info ni ichidagi narsalarga padding-right(left) lar berish o'rniga, Product-info ni o'ziga padding berish ham oson ham ma'qul (tashqaridan ichkarga ishlaymiz!!)

**Comment by vayvoo** [comment]
all margin's fixed
